### ISSUE TITLE
Tabella sfide DB

### ISSUE THREAD

**Issue by smsdiego** [BitPrepared/dreamland-wp-plugins#110]
generali: le sfide speciali sono messe come imprese (invece sono missioni) 

id 13,14,15,16 (la sq tigri reggio calabria 17 che si è registrata a tutto) protagonisti a 0 <---- x questa sq ho scritto al capo reparto x capire come mai si sono iscritti a tutto da avventura a maglieria... vediamo cosa dicono

**Comment by yoghi** [comment]
è ancora valido?

**Comment by smsdiego** [comment]
la prima parte è da correggere

la seconda non hanno risposto

**Comment by yoghi** [comment]
"le sfide speciali sono messe come imprese (invece sono missioni)" non mi pare chiaro cosa c'è che non va, vuoi dire che ogni volta che uno partecipa ad una sfida speciale diventa impresa?
