### ISSUE TITLE
termine resoconto e invio serve notifica visisva

### ISSUE THREAD

**Issue by smsdiego** [BitPrepared/dreamland-wp-plugins#127]
una volta inviato il resoconto serve qualche notifica o popup, o indirizzamento ad altra pagina, che permetta alle sq di capire cosa è successo, ora inseriscono il testo ecc.. e quando si preme il bottone (invia revisione <- nota c'è una issue da cambiare il testo), si rimane nella stessa pagina senza capire cosa è successo

**Comment by michele-carignani** [comment]
Adesso si ritorna alla dashboard e una notifica conferma l'avvenuta chiusura del racconto
