### ISSUE TITLE
vista stat_partecipantisfide

### ISSUE THREAD

**Issue by smsdiego** [BitPrepared/dreamland-wp-plugins#130]
non funziona più. mancano sfide completamente, altre sono messe su più righe

**Comment by yoghi** [comment]
Il problema è che molte sfide sono state registrate con permalink giusto ma idsfida sbagliato.

SELECT idsfida,titolo,SUBSTRING(permalink,37) FROM `iscrizionesfida` group by idsfida,titolo
ORDER BY `iscrizionesfida`.`idsfida` ASC

sino che id 255 è per più sfide.

**Comment by yoghi** [comment]
Fixato, ci deve essere stato un problema durante l'ultimo update di db.
