### ISSUE TITLE
Beta - pagina racconti

### ISSUE THREAD

**Issue by smsdiego** [BitPrepared/dreamland-wp-plugins#137]
La pagina racconti x i capi così come è ha poco senso
le modifiche si applicano anche se non dovrebbero essere applicate, con le fnzionalità abilitate si rischia solo di fare pasticci

inoltre non possiamo limitarci alla chiusura da link mail visto i capini con le mail
nella pagiana racconti deve esserci la possibilità del capo di raggiungere la stessa pagina del link della mail

**Comment by michele-carignani** [comment]
Sistemato
