### ISSUE TITLE
link chiusura racconto mail capo reparto

### ISSUE THREAD

**Issue by smsdiego** [BitPrepared/dreamland-wp-plugins#138]
Per approvare il resoconto il link del capo reparo deve portarlo prima alla pagina di login e poi al resoconto, altrimenti non si capisce che bisogna loggarsi e compare pagina non trovata

**Comment by michele-carignani** [comment]
Purtroppo il plugin che usiamo sovrascrive i redirect dopo tutti i login, quindi il capo riceve le iscrizioni per loggarsi nella mail e deve visitare lui il sito (deve visistare la propria bacheca).
