### ISSUE TITLE
(Prioità alta) Portal- Radio button sfida non superata

### ISSUE THREAD

**Issue by smsdiego** [BitPrepared/dreamland-wp-plugins#139]
Nel caso sia selezionato il no in portal alla chiusura sfida , prima di passare a portal sulla pressione del botone finale deve comparire un messaggio tipo "Attenzione: se dichiari la sfida non superata non potrai fare il resoconto e condivide la sfida, Procedi comunque ? - mettere la possibilità si-no)

**Comment by michele-carignani** [comment]
Lato wordpress: riceve come parametro della richiesta 'superata' con valori 'true' o 'false'.
Se non è superata non crea il racconto sfida, cambia lo stato in 'Non superata' e logga l'evento.

**Comment by michele-carignani** [comment]
il parametro utilizzato è 'successo' sempre con valori 'true' o 'false'
