### ISSUE TITLE
(priorità bassa) Testo mail EG su racconto respinto

### ISSUE THREAD

**Issue by smsdiego** [BitPrepared/dreamland-wp-plugins#140]
testo mail a eg quando respinto da cambiare legermente causa piccoli errori in

Ciao,
Il tuo caporeparto ha visto il racconto sfida che hai mandato e ha trovato qualcosa da migliorare. Parla direttamente con lui/lei e modificalo nuovamente. Puoi trovare il racconto nel menù della bacheca alla voce 'Racconti Sfida'

**Comment by michele-carignani** [comment]
Corretto
https://github.com/BitPrepared/dreamland-wp-plugins/blob/master/dreamers-sfide/dreamers-sfide.php#L1218
