### ISSUE TITLE
Racconti sfide viewer

### ISSUE THREAD

**Issue by smsdiego** [BitPrepared/dreamland-wp-plugins#153]
Ci vorrebbe un viewer per le foto caricate nelle sfide,
cosi da poter scorrere fra le foto caricate dai ragazzi.
Attualmente bisogna aprire le foto ad una ad una, e poi richiudere per cliccare sulla successiva...

**Comment by michele-carignani** [comment]
Risolto col plugin https://wordpress.org/plugins/wp-lightbox-2/
